version: "3.9"
volumes:
  db:
  gems:
services:
  db:
    image: postgres:14
    volumes:
      - db:/var/lib/postgresql/data
    env_file: .env.development
  web:
    build: .
    # Redundant with Dockerfile. Remove if everything works
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - gems:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env.development
