version: "3.9"
volumes:
  db:
  gems:
services:
  db:
    image: postgres:14
    volumes:
      - db:/var/lib/postgresql/data
    env_file: .env
  web:
    build: .
    volumes:
      - .:/app
      - gems:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    stdin_open: true
    tty: true
  test:
    image: rails_web
    volumes:
      - .:/app
      - gems:/usr/local/bundle
    depends_on:
      - db
    environment:
      RAILS_ENV: test
    env_file: .env
